apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gateway-project
  namespace: argocd
spec:
  description: Envoy Gateway GitOps Project

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
