apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-infra
  namespace: argocd
spec:

  source:
    repoURL: https://github.com/Kaushikvenkatraj/kubernetes-manifests
    targetRevision: HEAD
    path: gateway

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
